### ISSUE TITLE
Error run rake redmine plugins migrate

### ISSUE THREAD

**Issue by tigefa4u** [buoyant/redmine_tweetbook#3]
why this error come? @buoyant #3 
my redmine version is

``` bash
Environment:
  Redmine version                2.4.2.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  3.2.16
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.4
  Mercurial                      2.1
  Cvs                            1.12.13
  Git                            1.8.3
  Filesystem                     
Redmine plugins:
  redmine_reddrop                1.0
```

``` bash
root@ip-172-31-17-118:/opt/bitnami/apps/redmine/htdocs# rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
undefined method `[]' for nil:NilClass
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_tweetbook/init.rb:18:in `block in <top (required)>'
/opt/bitnami/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

**Comment by buoyant** [comment]
Please put your social links api keys in config/settings.yml
